### ISSUE TITLE
尝试用AES的CBC模式加密失败

### ISSUE THREAD

**Issue by Calabash-Boy** [HiKit/AddressableAESEncrypt#1]
大佬您好呀,看了您的源码,我尝试用项目中已有的CBC加密方案进行加密:

`
private void EncryptBundleWithAES(string bundlePath)
{
    Debug.Log("加密bundle: " + bundlePath);
    var bytes = File.ReadAllBytes(bundlePath);
    var encryBytes = GVAESUtil.AESEncryptedData(bytes);
    File.WriteAllBytes(bundlePath, encryBytes);
}
`

对应的,我也在自定义的BundleProvider中两个关键位置进行了解密
[CBC加密.zip](https://github.com/user-attachments/files/15543761/CBC.zip)
我扔了一个zip文件,您有时间的话请瞅一眼吧,救救孩子= =

从原理上来说,我在加载本地包和加载远端包的时候都进行了拦截,应该没问题,但是在手机上运行时直接报错了:

> Failed to decompress data for the assetbundle "memory"

网上说是包体已经是非法的了,我有点奇怪,只是换了一种加密方式,会导致这个问题吗?

**Comment by HiKit** [comment]
加点日志，看下走解密方法了吗
如果调用正常，那就对比下加密前的bundle以及解密后的bundle，按字节进行对比
最后再对比下crc

**Comment by Calabash-Boy** [comment]
好  我试试在编辑器下进行调试吧 真机调试要加的日志太多了

**Comment by suitun** [comment]
> 加点日志，看下走解密方法了吗 如果调用正常，那就对比下加密前的bundle以及解密后的bundle，按字节进行对比 最后再对比下crc

大佬，我看了一天你的代码，发现有两处特别的地方，一个是避开了使用DownloadHandler的子类DownloadHandlerAssetBundle，一个是安卓平台的处理，有一点比较疑惑，安卓平台为什么要用WebRequest来读取Bundle呀？安卓的ab包或者说路径有什么坑么
