### ISSUE TITLE
这是关于Unity版本的问题。

### ISSUE THREAD

**Issue by dev-shinyu** [HiKit/AddressableAESEncrypt#2]
你好，我正在进行一个2D项目，因此故意没有使用2D问题较多的Unity 2022，而是使用目前最新版本的Unity 2021 LTS。我看到一些示例好像只能在Unity 2022中运行。如果我想在Unity 2021中运行这些示例，该怎么做呢？

Hello, I am currently working on a 2D project, so I have deliberately chosen not to use Unity 2022, which has many 2D issues, and instead I am using the latest version of Unity 2021 LTS. I noticed that some samples seem to only work in Unity 2022. How can I make these samples work in Unity 2021?

**Comment by HiKit** [comment]
基于Addressable做的扩展，逻辑上和unity版本无关，当时的版本：Addressable 1.21.9
